### ISSUE TITLE
error when starting container

### ISSUE THREAD

**Issue by ThaMattie** [tekgator/docker-hd-idle#5]
When I deploy this the container keeps restarting with error:

standard_init_linux.go:228: exec user process caused: exec format error

Using it on pine64, with OMV, docker, portainer

**Comment by tekgator** [comment]
Since it is an GO error it seems to be coming from hd-idle directly.

Are you running OMV as a VM e.g. on Proxmox? If so I think the idling function will only work if you pass through the PCIE controller where the HDD is connected to.

Are you running the container PRIVILEGED as described?

`docker run -d \
  --name hd-idle \
  --privileged \
  -v /dev:/dev \
  tekgator/docker-hd-idle:latest`


If yes the only other options I see is to check whether:

1. The LEGACY version is working: https://github.com/tekgator/docker-hd-idle#legacy-version
2. Install hd-idle directly onto OMV and see if it is working there.

**Comment by ThaMattie** [comment]
I installed OMV directly on a Pine-64 with armbian. The container is running privileged. Legacy also doesn't seem to work.
This is my compose file:

```
version: "3"

services:
  hd-idle:
    image: tekgator/docker-hd-idle:latest
    container_name: hd-idle
    privileged: true
    environment:
      LEGACY: 1    #uncomment to use legacy version of hd-idle
      IDLE_TIME: 0
      DISK_ID1: /dev/disk/by-id/usb-NORELSYS_106X_0123456789ABCDE-0:0
      DISK_CMD1: ata
      IDLE_TIME1: 600
    volumes:
      - /dev:/dev
      - /srv/dev-disk-by-uuid-ABCDE01234567890/Config/HDIdle:/config
    restart: unless-stopped
 
```
I have yet to try running it on OMV directly....
